# nixos-unstable 2025-09-30 "25.11pre-git"
# generated by update-nixpkgs

import (builtins.fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/e9f00bd893984bc8ce46c895c3bf7cac95331127.tar.gz";
  sha256 = "0s2mhbrgzxlgkg2yxb0q0hpk8lby1a7w67dxvfmaz4gsmc0bnvfj";
})
